export const genericProfanityList: string[] = [
    'fuck',
    'crap',
    'shit',
    'piss',
    'puss',
    'pussy',
    'pussies',
    'asshole',
    'bullshit',
    'bitch',
    'son of a bitch',
    'tit',
    'prick',
    'twat',
    'punani',
    'cock',
    'dick',
    'dickhead',
    'bastard',
    'motherfucker',
    'wanker',
    'cunt',
    'slut',
    'whore'
]
